# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ipiranga' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ipiranga

 pod 'fluigsdk', :git => 'https://github.com/fluig/fluigsdkios', :branch => 'develop'

  target 'IpirangaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IpirangaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
